### ISSUE TITLE
An error occurred and all environment variables were deleted

### ISSUE THREAD

**Issue by sladkoff** [HiDeoo/vercel-env-push#20] opened 2023-01-25 17:09 UTC
### Describe the bug

I ran the following command:

```bash
npx vercel-env-push .env.local development
```

It showed me a preview with:

> Preparing environment variables push from '.env.local' to **development**.
> The following environment variables will be pushed:
> ...

It failed with:

```
Do you want to push these environment variables? (Y/n) Y
✖ Pushing environment variables
Something went wrong: Unable to remove environment variable 'AUTH0_SECRET' from 'development'.
Error: Command failed: npx --yes vercel env rm AUTH0_SECRET development -y
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /Users/username/.npm/_npx/69f9afb961c37556/node_modules/@vercel/node
npm ERR! dest /Users/username/.npm/_npx/69f9afb961c37556/node_modules/@vercel/.node-CgMrNk8Z
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/Users/username/.npm/_npx/69f9afb961c37556/node_modules/@vercel/node' -> '/Users/username/.npm/_npx/69f9afb961c37556/node_modules/@vercel/.node-CgMrNk8Z'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2023-01-25T16_19_39_652Z-debug-0.log

    at ChildProcess.exithandler (node:child_process:400:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
```

I refreshed the Environments in the Vercel UI - they were all gone. Note that I had variables for Development, Preview and Production environments.

Hint: This might be a Vercel problem because the variables were previously shared between the different environments. This tool might be able to handle that though.

### To Reproduce

See above.

### Expected behavior

The Preview and Production environment variables should not have been deleted...

### How often does this bug happen?

Only once

**Comment by HiDeoo** [comment] 2023-01-26 09:49
Thanks for the report.

From the error message, it looks like the error is related to a rename operation issue related to `npx` with the `@vercel/node` package.

The only file system operations done by `vercel-env-push` is pretty much only [checking that a file exists](https://github.com/HiDeoo/vercel-env-push/blob/771aaf31f8215efc64801d271031364af66bfa44/src/libs/file.ts#L8) and [reading a file](https://github.com/HiDeoo/vercel-env-push/blob/771aaf31f8215efc64801d271031364af66bfa44/src/libs/file.ts#L12).

Altho, `npx` is indeed used under the hood to run the `vercel` command. From a quick search, it looks like this is an error some people are randomly encountering when using `npm` or `npx`:

- https://stackoverflow.com/questions/71145130/npm-err-code-enotempty-npm-err-syscall-rename
- https://stackoverflow.com/questions/73415687/im-facing-errors-in-terminal-after-typing-npx-react-native-init-awesomeproject
- https://stackoverflow.com/questions/73847968/unable-to-install-react-in-linux

Altho, from these various threads, it looks like there is no obvious cause or solution. Some people are talking about this being Linux related, some others indicate a permission issue, and some other recommend just deleting the specified folders.

> This might be a Vercel problem because the variables were previously shared between the different environments.

I just tried to repro this scenario, e.g. having a `test` variable setup on Vercel shared between the `Production`, `Preview` and `Development` environments and updating it using `vercel-env-push` using the exact same command you used (`npx vercel-env-push .env.local development`), and no error was thrown.

> I refreshed the Environments in the Vercel UI - they were all gone.

Unfortunately, in this scenario described just above, this is a Vercel limitation. If you have a single variable setup on Vercel shared between multiple environments, it is not possible to remove this variable only for a specific environment using their CLI.

In the following screenshot for example, I have a `testA` variable shared between the `Development` and `Preview` environments.

<img width="920" alt="Screenshot 2023-01-26 at 10 37 24" src="https://user-images.githubusercontent.com/494699/214803598-e5fad379-b56f-4b77-a5b2-53ebe672f9e3.png">

Even tho their CLI help kinda indicates removing a variable from a specific environment should be possible:

<img width="461" alt="Screenshot 2023-01-26 at 10 38 18" src="https://user-images.githubusercontent.com/494699/214803809-04803c02-537b-4fbb-a81e-de87388fde3b.png">

Executing `npx vercel env rm testA development` will remove the variable from both environments:

<img width="847" alt="Screenshot 2023-01-26 at 10 39 51" src="https://user-images.githubusercontent.com/494699/214803995-5eca167a-886a-4681-b3fb-a6490b85b543.png">

This command will only work as we would expect if you have 2 *different* variables with the same name configured for different individual environments.

--- 

As it looks like the issue is not directly related to `vercel-env-push`, I'll close this issue altho, if you have any more informations or any indications I'm wrong, do not hesitate to comment on this issue and I'll re-open it right away to investigate.

**Closed by HiDeoo** 2023-01-26 09:49 UTC
